name: Iptables
description: Apply iptables rules
version: 1.0.0
slug: iptables
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
privileged:
  - NET_ADMIN
options:
  Oneshot: false
schema:
  Oneshot: bool
